---
- name: Install Apache
  apt: 
    name: apache2
    state: present
  tags: 
    - apache
    - install
  
- name: Enable Apache modules
  apache2_module: 
    name: {{ item }} # Here {{ item }} is the name of the module in the loop
    state: present 
  loop: # These are the modules to be enabled
    - rewrite 
    - ssl
  notify: Restart Apache # Triggers the Restart Apache handler 
  tags: 
    - apache 
    - config 

- name: Create Apache vhost 
  template: 
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ apache_domain }}.conf
  notify: Reload Apache
  tags:
    - apache
    - config

- name: Enable Apache vhost 
  command: a2ensite {{ apache_domain }}.conf # The a2ensite command is an Apache module for enabling domains
  args: 
    creates: /etc/apache2/sites-enabled/{{ apache_domain }}.conf
  notify: Reload Apache
  tags: 
    - apache
    - config

- name: Verify Apache is running
  service: 
    name: apache2
    state: started
    enabled: yes
  tags: 
    - apache 
    - service 

